[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64
#Mirror=https://mirror.hs-esslingen.de/debian
Repositories=main contrib non-free non-free-firmware
#RepositoryKeyFetch=true
#RepositoryKeyCheck=false

[Output]
Format=directory
OutputDirectory=mkosi.output

[Content]
Bootable=false
Locale=en_US.UTF-8
Keymap=de
Timezone=Europe/Berlin
Hostname=nextcloud-db-1
RootShell=/usr/bin/bash
RootPassword=helloworld
Packages=
    systemd
    systemd-resolved
    ssh
    nano
    polkitd
    iproute2
    bash-completion
    curl
    unzip
    dialog
    python3
    # apache
    apache2
    libapache2-mod-php
    # db
    mariadb-server
    # php
    php
    php-gmp
    php-bcmath
    php-gd
    php-json
    php-mysql
    php-curl
    php-mbstring
    php-intl
    php-imagick
    php-xml
    php-zip
    php-fpm
    # memory cache
    php-apcu
    # redis
    # php-redis
    # redis-server

[Build]
PackageCacheDirectory=mkosi.pkgcache
CacheDirectory=mkosi.cache
WorkspaceDirectory=/home/frida/mkosi/mkosi.workspace
ToolsTree=yes
ToolsTreeDistribution=debian
ToolsTreeRelease=trixie
# Tell mkosi to explicitly include the bootloader binaries in the build environment tools tree:
ToolsTreePackages=systemd-boot-efi
WithNetwork=true
Incremental=true
