<?php
$CONFIG = array (
  'passwordsalt' => 'vQu1Mly8aIFKh1T25DnBwGj2ePQc/6',
  'secret' => 'g6iUfm5C5ot/P/fyOQO4S8elM/oWuCyxOqbTpW6MFcnPDSG9',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'nextcloud.unonweb.de',
    2 => '192.168.10.50',
  ),
  'trusted_proxies' => 
  array (
    0 => '192.168.10.50',
    1 => '192.168.10.0/24',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '33.0.5.1',
  'overwrite.cli.url' => 'https://nextcloud.unonweb.de',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'nextcloud.unonweb.de',
  'default_language' => 'de',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'admin',
  'dbpassword' => 'heywirmüsssenreden,oderhasstduetwaeinproblemmitmir?',
  'installed' => true,
  'instanceid' => 'oc1q27goyk1b',
  'auth.bruteforce.protection.enabled' => true,
  'auth.webauthn.enabled' => true,
  'mail_domain' => 'unonweb.de',
  'mail_from_address' => 'support',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.strato.de',
  'mail_smtpport' => '465',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => true,
  'mail_smtpname' => 'support@unonweb.de',
  'mail_smtppassword' => 'TqDx#G64~gP47JU%mM3$',
  'mail_smtpsecure' => 'ssl',
  'loglevel' => 1,
  'maintenance_window_start' => 1,
  'maintenance' => false,
  'theme' => '',
  'updater.secret' => '$2y$12$gRoqemXb20ITxzgqCRnGde19pyxXJX6S.Y5Tf8AXRTtRuxnalzOOS',
  'memcache.local' => '\OC\Memcache\APCu',
);
